### ISSUE TITLE
Re-evaluate wether VTT_hash has a one-to-one mapping with a Patient

### ISSUE THREAD

**Issue by davidverweij** [ideafast/middleware-services#25]
Ideally yes, only one patient will use one login credential (which we provide). However, some study sites have unfortunatly reused that once or twice between patients, so this 1-1 is not true for some historical data, and may not be true in the future. 

Maybe make a note here to edit this once we have real data on S3 to work against, e.g., from Newcastle?

_Originally posted by @jawrainey in https://github.com/ideafast/middleware-services/pull/21#discussion_r568565097_

**Comment by jawrainey** [comment]
Given the recent development of the UCAM API that has a `/vtt/` endpoint because credentials may be shared across patients, then we need to modify the VTT pipeline to account for this and use the new endpoint?

**Comment by davidverweij** [comment]
True - I feel this relates mostly to #45. This issue was related to overlapping VTT hashes, which has actually been resolved by VTT by adding the wear times in the folder names. Will close this issue and continue on the UCAM endpoint in #45.
