### ISSUE TITLE
Mock download in data pipeline when running locally

### ISSUE THREAD

**Issue by jawrainey** [ideafast/middleware-services#28]
When running pipelines locally we do not want to download files from external manufacters primarily due to file sizes. As such, we could have something similar to the following:

Add an environmental variable `IS_LOCAL=True` to our `.env` configuration, then where we call `download_file` in each pipeline we could decorator it. The decoractor could then not call the download_data method if the env variable is set:

```python
def skip_if_is_local(download_data):
 def wrapper(session, record_id):
   if config.is_local:
     file_path = Path(config.storage_vol) / f"{​record_id}​.h5" # NOTE: hard-coded dreem extension
     write_json(file_path, {​}​)
     # NOTE: we do not run the download method below ;-)
   else:
     download_data(session, record_id)
 return wrapper

@skip_if_is_local
def download_file(session: requests.Session, record_id: str) -> bool:
   ....
```

This above implementation is for dreem, but of course the parameters for `download_file` may vary, e.g., such as for [VTT SMA](https://github.com/ideafast/middleware-services/blob/master/data_transfer/devices/vttsma.py#L103): 

```python
def download_files(bucket: Bucket, patient_hash: str, export_date: str,) -> bool: 
   ...
```
Related to this, you will see above that I have hard-coded the extension. This is quite an important detail as the shared task expected specific file types: 

https://github.com/ideafast/middleware-services/blob/a6ba0ad3e9040a0c6efd78ca4c2caf4adcf28264/data_transfer/tasks/shared.py#L6-L10 

Therefore:

1. Decorator above should accept filetype as a parameter
2. Accept arbitary arguments (**args) where the first one must be the filename or keyword argument (**kwargs) such that we can specific `kwargs['record_id']`

This might result in something like the following (not tested):

```python
def skip_if_is_local(filetype):
    def decorator(download_data):
        def wrapper(*args):
            if config.is_testing:
                file_path = Path(config.storage_vol) / f"{args[0]}{filetype}"
                write_json(file_path, {})
            else: 
               download_data(session, record_id)
        return wrapper
    return decorator

from data_transfer.tasks.shared import FILE_TYPES

@skip_if_is_local(FILE_TYPES['DRM'])
def download_file(session: requests.Session, record_id: str) -> bool:
   ....
```

**Comment by jawrainey** [comment]
Simple solution to the above might be to store the file extension within the `filename` in `Record`? Since  there is clearly a minor dependency between data download and preparation when there shouldn't be

**Comment by davidverweij** [comment]
Just an option, we could catch/implement the decorator a level higher in the DAG in `main.py` at `dreem_tasks.task_download_data(study_site, record.id)` and `vttsma_tasks.task_download_data(record.id)`. This way, we could pass the Enum type to ensure the correct mocked data file, but do need to upload the record to indicate that the download is successful. Luckily, this is the same for all devices (at the moment). Then we would have:

```python
# in tasks > dreem.py AND vttsma.py
@skip_if_is_local(record_id, utils.DeviceType.SMA)
def task_download_data(study_site: str, mongoid: str) -> str:
    # dreem has study site, vtt has not - but we can ignore either way
   ....
```

I am not too experienced with decorators, so I am not sure how to proceed with `task_download_data()` if skip_local is False. What do you think?

**Comment by davidverweij** [comment]
Since I've written a few tests and mocked the DB and others, I'd argue we should set this as a test and use that to mock downloading a file as shown in one of the tests - rather than create a module-level override to do so. Thoughts?
