### ISSUE TITLE
Use local DMP for integration testing

### ISSUE THREAD

**Issue by jawrainey** [ideafast/middleware-services#33]
As noted in #28, it is critical to test the complete pipeline and all the external services we interact with. While we can mock those interactions and unit test our interfaces (e.g., the upload functionality in dmpy) we might also consider using a test version of the DMP that accepts files to mirror intended use, i.e., integration testing.

> This returns `True` at the moment - which makes me think. Can we set up a dummy DMP (preferably not local, a docker volume?) to receive the uploaded files? I presume we want to test the processes multiple times before committing to the DMP

_Originally posted by @davidverweij in https://github.com/ideafast/middleware-services/pull/14#r565968163_

**Comment by davidverweij** [comment]
What do you think we need to do so? I assume we need some insights in how the DMP is currently storing data, and responding to requests? Alternatively, a test environment in the DMP might be quicker to set up. Should we pull in WP5 in this discussion?

**Comment by davidverweij** [comment]
Given our current use of a test database on the DMP - I'd argue we can close this issue; @jawrainey?
