### ISSUE TITLE
Update MongoDB record structure and pipeline protocol

### ISSUE THREAD

**Issue by davidverweij** [ideafast/middleware-services#34]
From @jawrainey: given we're using mongodb, we could have a "meta" attribute on the Record that stores relevant metadata in json format for specific devices that we can access as needed? 
 
That way, we don't have to continue adding device specific attributes

**Comment by davidverweij** [comment]
In light of this - I am still a bit worried about the use of the `uid`s (provided by the manufacturer) as a unique identifier (not `_id` but `filename`) to check for past downloads in the MongoDB. If we need this logic, I'd suggest to add a prefix to ensure separation of manufacturer uids. In addition these filenames link to specific files/records to download, and not necessarily for patient identifiers. I am unfamiliar how this is with Dreem - but it already poses an issues with VTT SMA if a patient occurs across data exports (and we keep mongoDB records live). 
### Suggestion
My suggestion then would be to add the `DeviceType` enum name value as prefix, such that we get things like:
- AX6-...
- DRM-...
- SMA-...
...

For BTF, each record has a uid. Each signal data has their own unique ID as well, thus we can use that for uids (given the prefix) in the mongoDB. 

For VTTSMA I would tightly couple the data export name to the mongoDB entry, as a patient hash might occur across data exports, but not if we include the wear period - as VTT already does in their exports. Thus the monogDB filename would be something akin to `SMA-qwertyuiop-01012020-02022020`. If we fear that we might get data exports with identical wear times and patient hashes across data exports - we might as well include the full pathname, i.e. `SMA-data_export_01012020-qwertyuiop-01012020-02022020`.

**Comment by jawrainey** [comment]
@davidverweij -- for dreem the `filename` is distinct as data generated on a device is unique. The mapping between patients who used the device's based on the `device_id` was a bit tricky for historical reasons. I can see that for VTT-SMA the filename hash may be duplicated given the application may have been logged in by multiple patients.

What's the benefits of storing the filename in the format above above over using the existing properties of `Record`, which  store this metadata, i.e., [`device_type`](https://github.com/ideafast/middleware-services/blob/master/data_transfer/schemas/record.py#L15) and the wear period ([`start_wear`](https://github.com/ideafast/middleware-services/blob/master/data_transfer/schemas/record.py#L18) and [`end_wear`](https://github.com/ideafast/middleware-services/blob/master/data_transfer/schemas/record.py#L19)?

Given each `Record` should be distinct, if we had two uses of the VTT app with the same `filename` then we can tell its different use via the other attributes, i.e., patient_id, wear time, etc that are retrieved from UCAM's DB?

**Comment by davidverweij** [comment]
Good point - the other fields do provide the uniqueness needed - though this does depend on ensuring these do not overlap / are mis-interpreted with overall study wear times.

RE: a metadata field - we are already storing a `...-meta.json` file in preparation of the file download. Can we nog simply use that to store more complex structured? E.g. for byteflies, this is a list of signals and files to download _per record_.

**Comment by jawrainey** [comment]
In principle wear times should not overlap as two patients cannot wear the same device at the same time, but in this case we depend on UCAM for accuracy? Likewise, might meant that for the VTT-SMA implementation we have to filter data by known wear periods.

re:metadata: @davidverweij -- sounds like a good idea to use `-meta.json` to store details about the raw data file. It may not be ideal for retrieving which data belongs to which device at a group level though, i.e, when preparing the data for upload. Perhaps if the metadata stores identifies which device (via its ID) and which body placement it belongs to (via UCAM).

As byteflies stores multiple files per device and because they are each downloaded individually, then each should become a distinct `Record` as it's associated with a datafile. This proposed metadata field (rather than `-meta.json`) could be useful when preparing the set of files to be uploaded, i.e., to move all the files for say one day for one patient to one folder in the format:

```
/patientid-deviceID-startWear-EndWear/
    /brain/
        ... data
    /ankle/
        ... data
   /heart/
       ... data
```

While we could easily move all data per patient based on wear time, do we want to format the data by devices above? We could use the sensor dot hash instead of the human-readable location. Likewise, do we want to be explicit in regards to which data belongs to which device and where it was worn? This information is (or will be) in UCAM's db. Food for thought 👍🏼

**Comment by davidverweij** [comment]
As we progress with the development of the pipeline, a few interesting needs/challenges arise that I'd like to discuss and propose. This touches upon the `metadata` field above and how we handle `Records` in relation to files to download and associated `...-meta.json` files. The [`refactor`](https://github.com/ideafast/middleware-services/compare/refactor) branch started on these needs.

In particular, I think we need to discuss the following architecture - some of which already agreed some open for discussion.

For each pipeline in the `data_transfer`, each result of a query to the manufacturer sensor recording is dissected into:
- a `...-meta.json` file containing metadata related to the overall recording
- each file that needs to be downloaded for this recording will then get: 
    - a `Record` in our MongoDB database
    - a `...-preprocessed.json` in cases where it is relevant to generate additional metadata for a specific file

## Hashing UIDs
Previously, we used the filename as a `uid` to check if we already have this file as a `Record` (to prevent duplicate downloads), though this proves more complex in structures where data is not provided on a per-recording basis (such as VTT, CamCog, etc) - or when multiple files are associated with one sensor recording. Instead, we can:
- Hash a manufacturers provided identifier (or anything that makes reference to a file unique) to use for diff's with our database. This means for example:
    - Dreem: the `uid` of the recording hashed (e.g. `"dreem_recording_id"` -> `"88b740..."`)
    - VTT: the full path to the file hashed (e.g. `"export/raw/patienthash_weartime/patienthash-geoln.json"` -> `"88b740..."`)
    - Byteflies: the uid of the signal/algorithm or a combination of both (e.g. `"recording_uid/signal_uid/algorithm_uid"` -> `"88b740..."`)

For brevity, I suggest to use `sha256` for hashing. I would also suggest to use Python's built-in hash library `hashlib`.

## MongoDB UID as temporary file name
The hashing made me wonder how we deal with uniqueness whilst downloading files in a shared folder - as we are doing now. A collision quickly becomes apparent when downloading audio data from two participants for VTT:
- `"export_date/files/participant1_hash/20201208T201219.29Z_main-eveningodd_Audio-Q-DateTime.wav"`
- `"export_date/files/participant2_hash/20201208T201219.29Z_main-eveningodd_Audio-Q-DateTime.wav"`

Storing the files with their original filenames will, then, not work. Storing the full path name will not work either due to conflict in the `/` separator. Hashes do not ensure uniqueness, but instead, since the `uid`s generated for each Mongo `Record` are unique, I suggest to use that ID for temporary file naming. So then, for example:
- `"export_date/files/participant1_hash/20201208T201219.29Z_main-eveningodd_Audio-Q-DateTime.wav"`
   - becomes: `"6026c0fc52114f798491c36f"`
- `"export_date/files/participant1_hash/20201208T201219.29Z_main-eveningodd_Audio-Q-DateTime.wav"`
   - becomes: `"6026c0fc52114f798491c373"`
- `"dreem_recording_id.h5"`
   - becomes: `"6026c0fc52114f798491c375"`

I'll have to look into whether we need the extensions (e.g. `wav`) in order for this to work or not. In the `taks_prepare()` stage, the names can then be returned to original using a `original_filename` field in the `Record`. 

## Skipping `task_prepare_data()` if one Record has failed
Lastly, if one of the `Records` fails at the download or pre-process stage, I'd argue that none of the files should be packaged and uploaded to the DMP. That means that in the `task_prepare_data()` method we need to query all Records that match a patientId, deviceId, and wear times, should be succeeded before proceeding.


---

The above suggest we alter the following parts of our code as follow (or alike):

```python
class Record(BaseModel):
    """
    Stores metadata pipeline information for each raw data file
    """
    # uid - also used in temporary file naming
    id: Optional[Any] = Field(alias="_id")

    # used to diff new downloads with history stored in MongoDB
    hash: str

    # to restore filename once prepared for upload
    original_filename: str  

    device_type: str
    device_id: str
    patient_id: str
    start_wear: datetime
    end_wear: datetime
   
    # meta data relevant to individual device pipelines. For VTT for example
    # this will hold the full path to the file for download
    meta: dict  

    # Each stage of the pipeline
    is_downloaded: Optional[bool] = False
    is_processed: Optional[bool] = False
    is_prepared: Optional[bool] = False
    is_uploaded: Optional[bool] = False
```

In utils, we would then use a hash function something like:

```python
def uid_to_hash(input: str, device_type: DeviceType) -> str:
    result = hashlib.sha256()
    # deviceType is used as a salt and to improve uniqueness across
    # devices (i.e. Dreem uid != Byteflies uid)
    result.update(device_type.name)
    result.update(input)
    return result.hexdigest()
```

Before uploading to the DMP, we would also then want to check if we have all files, i.e.:

```python
def batch_upload_data() -> None:
    skip_unfinished_folders = check_unfinished_records()
    folders_to_upload = [p for p in config.upload_folder.iterdir() if p.is_dir() and p not in skip_unfinished_folders]
```
with `check_unfinished_records()` being something like:
```python
def check_unfinished_records() -> List[str]:
    unfinished_DMP_folders = set([
        f"{doc.patient_id}-{doc.device_id}-{doc.start_wear}-{doc.end_wear}"
        for doc in _db.records.find({"is_preprocessed": False})
    ])
    return unfinished_DMP_folders
```

Thoughts @jawrainey @ColinBD? I'd suggest to amend these changes through the `refactor` branch. Happy to do so.

**Comment by jawrainey** [comment]
> Hashing UIDs ...

This sounds like a great solution. It's worth noting that we need to store the original UIDs as they are used in subsequent queries to dreem/byteflies, so if they were hashed we would have to unhash them. I think this is resolved in your proposed `original_filename` above? Might be worth naming it `manufactuer_id` since it's not necessarily a filename ... although I suppose it may not be an ID either 👀 ?

> MongoDB UID as temporary file name ... The hashing made me wonder how we deal with uniqueness whilst downloading files in a shared folder - as we are doing now. A collision quickly becomes apparent when downloading audio data from two participants for VTT:

Good point! We could use the Mongo UID since this would be created prior to download (when creating a record in `meta`). An alternative approach would be to place patient-specific data in a folder in `/input/` per device, e.g. `/input/PatientOne/DeviceOne/`. This would remove the need for unique file names or colisions between patients since they are unique on the servers we retrieve them from and also means we can more easily debug if needed without having to run many db queries :)

> Skipping task_prepare_data() if one Record has failed ... Lastly, if one of the Records fails at the download or pre-process stage, I'd argue that none of the files should be packaged and uploaded to the DMP. That means that in the task_prepare_data() method we need to query all Records that match a patientId, deviceId, and wear times, should be succeeded before proceeding.

This is a good point and most relevant to VTT/Byteflies were there exists multiple data for an individual "session", and the proposed method seems great. Having your proposed method in `batch_upload` would be ideal

**Comment by davidverweij** [comment]
Sounds good, agreed on the folder creation for patient-relevant data. I'd then even suggest to create the appropriate DMP-style named folder at that stage. 
E.g.:
```python
download_metadata(self) -> None:
        ...
        for item in unknown_records:
                # logic copied from task_prepare_data()
                data_folder_name = f"{patient_id}-{device_id}-{start_wear}-{end_wear}"
                download_destination = config.data_input / data_folder_name
            
                if not destination.exists():
                    destination.mkdir()
                ...
                
                record = Record(
                          ...
                          download_destination = download_destination
                          ...
                )
    
                create_record(record)

```

Then a `Record` could store the destination for downloading the next step.

**Comment by jawrainey** [comment]
Sounds great and that could also potentially simplify the subsequent logic in `prepare` stage? I assume here `start_wear` and `end_wear` are the start/end periods of when the file was created? This means that for example, for VTT there would be many files in this one folder, then for dreem there would be one folder per record saved.

Would that mean the logic in `prepare` would take the min/max of the `is_prepared` files that have yet to be uploaded, and move those folders into an individual folder? Foe example, if we we have a 3 day wear period, the meta stage would create:

```
/PATIENT_ID-DEVICE_ID-DAY1-DAY1
  ... data
/PATIENT_ID-DEVICE_ID-DAY2-DAY2
  ... data
/PATIENT_ID-DEVICE_ID-DAY3-DAY3
  ... data
```

Then the `prepare` stage would move those folders into `/upload` as follows:

```
/PATIENT_ID-DEVICE_ID-DAY1-DAY3
  ./PATIENT_ID-DEVICE_ID-DAY1-DAY1
  ./PATIENT_ID-DEVICE_ID-DAY2-DAY2
```

**Comment by davidverweij** [comment]
Yes, it is indeed **not** the UCAM times.  But the above does mean we would need to re-read all folder names to determine the min-max of the wear times.

Since we want to upload all data that we have about a patient that we do not have done so yet, I think we can omit the days indicators within the folder names. Especially since _within_ manufacturer data uniqueness is ensured. I.e.

```
/PATIENT_ID-DEVICE_ID
  ... data day 1
  ... data day 2
  ... data day 3
```

We can then (as before) get the min and max of weartimes in that folder and 'simply' rename the top-folder to
```
/PATIENT_ID-DEVICE_ID-START-END
  ... data day 1
  ... data day 2
  ... data day 3
```

This made me think if something goes 'wrong' with a download, and let's say it takes us longer to solve than our next execution of the pipeline, we need to avoid that newer data is pulled down in the above named folder. To make things more confusing - but separating previous and new executions of the pipeline, I would suggest to add one higher level folder to separate these executions. I.e.:

```shell
/PIPELINE_2021_12_16
    /PATIENT_ID-DEVICE_ID
      ... data day 1
      ... data day 2
      ... data day 3

    # e.g. there might be an issue with this one, but this data is then not pulled into next day's execution
    /PATIENT_ID-DEVICE_ID
      ... data
    /PATIENT_ID-DEVICE_ID
      ... data day 1
      ... data day 2
/PIPELINE_2021_12_17
    /PATIENT_ID-DEVICE_ID    
      ... data day 1
      ... data day 2
```

**Comment by jawrainey** [comment]
> This made me think if something goes 'wrong' with a download, and let's say it takes us longer to solve than our next execution of the pipeline, we need to avoid that newer data is pulled down in the above named folder. To make things more confusing - but separating previous and new executions of the pipeline, I would suggest to add one higher level folder to separate these executions. see below:

Certainly worth considering, though we would likely have the start/end run of the pipeline via logs and metadata? I believe we can see this metadata via the airflow dashboard -- worth investigating further

> ALTERNATIVELY we could also not 'care' about newer data being pulled into this folder. It gives the pipeline another chance to download failed downloads again, and the only difference is a larger upload to DMP.

If the `prepare` stage operates on files (as it does not) rather than folder, then it is fine that all files go into `/input/patient_id-device_id/` since `prepare` would only move the individual files of interest 👍🏼  This keeps it simple without having to worry too much about folder structures, which was the intended purpose of current implementation

**Comment by davidverweij** [comment]
Agreed, good points. Might be worth having a pair-programming session to iron this out - and then we can reflect these changes into the Miro Board.
